docs:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - '!frontend/**'
      - '!backend/**'
      - '!.github/**'
      - '!scripts/**'
      - '!.gitignore'
      - '!.pre-commit-config.yaml'

internal:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - 'scripts/**'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '!**/*.md'
      - '!frontend/**'
      - '!backend/**'
