blank_issues_enabled: false  # disable “open a blank issue”
contact_links:
  - name: ❓ Questions or Support
    url: https://example.com/support
    about: Please use this link for general questions.
