name: 💡 Feature Request
description: Suggest an idea or improvement
title: "[Feature] <short summary>"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe your idea.
      placeholder:
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important or useful?
